name: EmergencySOS

options:
  bundleIdPrefix: org.emergencysos
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

targets:
  EmergencySOS:
    type: application
    platform: iOS
   
       sources:
      - path: Sources
      - path: Assets.xcassets
        buildPhase: resources

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.emergencysos.emergencysos
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "برای ارسال موقعیت در شرایط اضطراری برنامه به موقعیت مکانی شما نیاز دارد."
       

    info:
      path: EmergencySOS-Info.plist
      properties:
        CFBundleDisplayName: EmergencySOS
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
